# Generated by Django 5.2.15 on 2026-06-09 15:59

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Backfill a unique slug for every existing job."""
    Job = apps.get_model('core', 'Job')
    used = set()
    for job in Job.objects.all():
        base = slugify(job.title) or 'job'
        slug = base
        n = 2
        while slug in used or Job.objects.filter(slug=slug).exclude(pk=job.pk).exists():
            slug = f"{base}-{n}"
            n += 1
        used.add(slug)
        job.slug = slug
        job.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_job_employment_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, null=True, unique=True),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
