# Generated by Django 5.2.15 on 2026-06-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_email_phone_to_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_deleted',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='is_deleted',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
