# Generated by Django 5.2.15 on 2026-06-11 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_resume_file_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='recruiter_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('shortlisted', 'Shortlisted'), ('phone_screen', 'Phone Screen'), ('interviewing', 'Interviewing'), ('offer_extended', 'Offer Extended'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='score_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='score_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resume',
            name='score_manually_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ResumeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_notes', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.resume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
