# Generated by Django 5.2.15 on 2026-06-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_resume_achievement_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='screening_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('needs_review', 'Needs Review'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
