# Generated by Django 6.0.5 on 2026-06-19 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_resume_screening_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('file_hash', ''), _negated=True)), fields=('job', 'file_hash'), name='uniq_active_resume_file_per_job'),
        ),
    ]
