# Generated by Django 5.2.16 on 2026-09-09 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_resume_uniq_active_resume_file_per_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='seen_status',
            field=models.CharField(blank=True, choices=[('unseen', 'Not Seen'), ('seen', 'Seen')], db_index=True, default='unseen', max_length=10),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['job', 'seen_status'], name='resume_job_seen_idx'),
        ),
    ]
