# Generated by Django 5.2.15 on 2026-06-28 09:58

import uuid
from django.db import migrations, models


def backfill_uuids(apps, schema_editor):
    """Populate any rows still missing a uuid before enforcing NOT NULL.

    Migration 0010 backfilled existing rows and the field has a default, so this
    is normally a no-op — but it guarantees the AlterField below can't fail on a
    legacy NULL (e.g. one inserted by a raw query or bulk_create).
    """
    Resume = apps.get_model('core', 'Resume')
    for pk in Resume.objects.filter(uuid__isnull=True).values_list('pk', flat=True):
        Resume.objects.filter(pk=pk).update(uuid=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_resume_uniq_active_resume_file_per_job'),
    ]

    operations = [
        migrations.RunPython(backfill_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='resume',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
