# Generated by Django 5.2.16 on 2026-09-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_resume_seen_status_resume_resume_job_seen_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assessments',
            field=models.JSONField(blank=True, default=list, help_text='Assessments emailed to a candidate when they are shortlisted'),
        ),
    ]
