# Generated by Django 5.2.15 on 2026-06-29 05:29

from django.conf import settings
from django.db import migrations, models


def backfill_dedup_key(apps, schema_editor):
    """Populate dedup_key for active, hashed rows before the unique constraint.

    Sets dedup_key = file_hash for the FIRST active row of each (job, file_hash);
    any pre-existing duplicates (possible on MySQL, where the old *conditional*
    constraint was silently never created) keep dedup_key = NULL so they are
    exempt and the new constraint can be added without failing on legacy data.
    Nothing is deleted.
    """
    Resume = apps.get_model('core', 'Resume')
    seen = set()
    qs = (
        Resume.objects
        .filter(is_deleted=False)
        .exclude(file_hash='')
        .order_by('job_id', 'id')
        .values_list('id', 'job_id', 'file_hash')
    )
    for pk, job_id, file_hash in qs:
        key = (job_id, file_hash)
        if key in seen:
            continue  # legacy duplicate -> leave NULL (exempt)
        seen.add(key)
        Resume.objects.filter(pk=pk).update(dedup_key=file_hash)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_resume_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resume',
            name='uniq_active_resume_file_per_job',
        ),
        migrations.AddField(
            model_name='resume',
            name='dedup_key',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.RunPython(backfill_dedup_key, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(fields=('job', 'dedup_key'), name='uniq_active_resume_dedup'),
        ),
    ]
