# Generated by Django 5.2.16 on 2026-09-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_job_assessments'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requisition_id',
            field=models.CharField(blank=True, help_text='Carried into the candidate and HR verification forms', max_length=64),
        ),
    ]
