# Generated by Django 5.2.15 on 2026-07-02 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_resume_uniq_active_resume_file_per_job_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('job.created', 'Job created'), ('job.updated', 'Job updated'), ('job.deleted', 'Job deleted'), ('job.restored', 'Job restored'), ('job.auto_closed', 'Job auto-closed'), ('resume.uploaded', 'Resume uploaded'), ('resume.deleted', 'Resume deleted'), ('resume.rescreen_requested', 'Resume rescreen requested'), ('resume.recruiter_status_changed', 'Resume recruiter status changed'), ('resume.score_overridden', 'Resume score overridden'), ('resume.screening_completed', 'Resume screening completed'), ('resume.screening_failed', 'Resume screening failed'), ('resume.screening_needs_review', 'Resume screening needs review'), ('interview.created', 'Interview created'), ('interview.updated', 'Interview updated'), ('interview.deleted', 'Interview deleted'), ('interview.evaluation_submitted', 'Interview evaluation submitted'), ('interview.eval_link_renewed', 'Interview eval link renewed'), ('interview.eval_link_deleted', 'Interview eval link deleted'), ('user.created', 'User created'), ('user.activated', 'User activated'), ('user.deactivated', 'User deactivated')], max_length=50)),
                ('entity_type', models.CharField(blank=True, choices=[('job', 'Job'), ('resume', 'Resume'), ('interview', 'Interview'), ('interview_evaluation', 'Interview Evaluation'), ('user', 'User')], max_length=32)),
                ('entity_id', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_entity_idx'), models.Index(fields=['-created_at'], name='audit_created_idx')],
            },
        ),
    ]
