# Generated by Django 5.2.16 on 2026-09-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_job_requisition_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='requisition_id',
        ),
    ]
