# Generated by Django 5.2.16 on 2026-09-30 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_job_requisition_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='onboarding_checklist',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='rejection_email_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='rejection_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='rejection_email_sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejection_emails_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resume',
            name='recruiter_status',
            field=models.CharField(blank=True, choices=[('new', 'New CV'), ('shortlisted', 'Shortlisted'), ('phone_screen', 'Phone Screening'), ('assessment', 'Assessment / Test'), ('interviewing', 'Interviewing'), ('selected', 'Selected'), ('info_received', 'Candidate Information Received'), ('bgv_completed', 'Background Verification Completed'), ('offer_extended', 'Offer Letter Sent'), ('pre_onboarding', 'Pre-Onboarding'), ('hired', 'Onboarded'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Changed by a recruiter'), ('auto', 'Updated automatically')], default='manual', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='core.resume')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
