# Generated by Django 5.2.16 on 2026-08-25 08:47

import apps.candidate_mapping.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_resume_uniq_active_resume_file_per_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('completed_steps', models.JSONField(blank=True, default=list)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_mappings_saved', to=settings.AUTH_USER_MODEL)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_mapping', to='core.resume')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_mappings_started', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_mappings_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'candidate mapping',
                'verbose_name_plural': 'candidate mappings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateMappingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=apps.candidate_mapping.models.upload_to)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='candidate_mapping.candidatemapping')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_mapping_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['question_key', 'uploaded_at'],
                'indexes': [models.Index(fields=['mapping', 'question_key'], name='cm_file_form_question_idx')],
            },
        ),
    ]
