# Generated by Django 5.2.17 on 2026-08-20 14:04

import apps.employee_form.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_resume_uniq_active_resume_file_per_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_expires_at', models.DateTimeField()),
                ('otp_hash', models.CharField(blank=True, max_length=128)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('current_step', models.CharField(default='section_a', max_length=50)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('invite_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_form_invites', to=settings.AUTH_USER_MODEL)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_form', to='core.resume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeFormFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=apps.employee_form.models.upload_to)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='employee_form.employeeform')),
            ],
            options={
                'ordering': ['question_key', 'uploaded_at'],
                'indexes': [models.Index(fields=['form', 'question_key'], name='ef_file_form_question_idx')],
            },
        ),
    ]
