# Generated by Django 5.2.17 on 2026-08-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeform',
            name='last_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='employeeform',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
