"""Question and choice labels of the pre-FINAL referee forms, for reading old replies."""

LEGACY_LABELS = {'employer': {'disciplinary_action': 'Was any formal disciplinary action taken against the '
                                     'candidate during employment?',
              'disciplinary_details': 'Substantiated and disclosable details, including the '
                                      'outcome',
              'employment_period': "Please confirm the candidate's employment period",
              'employment_status': 'Employment status at the time of separation',
              'had_promotion': 'Did the candidate receive any promotion(s) during employment?',
              'integrity_concerns': 'Were there any substantiated integrity, fraud, harassment, '
                                    'misconduct, confidentiality or serious compliance concerns?',
              'integrity_details': 'Factual details you are authorised to disclose',
              'last_designation': "Please confirm the candidate's last / most recent designation",
              'promotion_details': 'Promotion / designation details',
              'rating_attendance': 'Attendance / punctuality',
              'rating_communication': 'Communication / collaboration',
              'rating_overall': 'Overall job performance',
              'rating_people_management': 'People management, if applicable',
              'rating_professionalism': 'Professional behaviour',
              'rating_quality': 'Quality / accuracy of work',
              'rating_reliability': 'Reliability / ownership',
              'rating_stakeholders': 'Relationship with customers / stakeholders',
              'rehire_eligible': 'Is the candidate eligible for rehire?',
              'rehire_explanation': 'Brief factual explanation',
              'separation_nature': 'Nature of separation',
              'separation_reason': 'Please confirm the reason for separation / leaving',
              'subordinates': 'Number of direct / indirect subordinates, if applicable',
              'verifier_department': 'Your department',
              'verifier_designation': 'Your designation',
              'verifier_name': 'Your name',
              'verifier_organisation': 'Organisation',
              'verifier_relationship': 'Your relationship to the candidate',
              'was_employed': 'Was the candidate employed by your organisation?'},
 'professional': {'anything_else': 'Is there anything else that would help us assess the '
                                   "candidate's suitability for employment?",
                  'candidate_role': 'What position / role did the candidate hold while you worked '
                                    'together?',
                  'conduct_concerns': 'To your direct knowledge, were there any serious conduct, '
                                      'integrity or disciplinary concerns relevant to employment?',
                  'conduct_details': 'Factual information you are authorised to disclose',
                  'development_areas': 'What development areas would you suggest for the '
                                       'candidate?',
                  'hire_again': 'Would you work with / hire the candidate again?',
                  'hire_again_explanation': 'Please explain any reservations',
                  'known_duration': 'How long have you known / worked with the candidate?',
                  'main_responsibilities': "What were the candidate's main responsibilities, to "
                                           'the best of your knowledge?',
                  'managed_others': 'Did the candidate manage people / vendors / key stakeholders?',
                  'managed_scope': 'Please briefly describe the scope',
                  'rating_communication': 'Communication skills',
                  'rating_integrity': 'Integrity / trustworthiness',
                  'rating_leadership': 'Leadership / people management, if applicable',
                  'rating_overall': 'Overall performance',
                  'rating_pressure': 'Ability to work under pressure',
                  'rating_problem_solving': 'Problem-solving / judgement',
                  'rating_professionalism': 'Professionalism / workplace behaviour',
                  'rating_quality': 'Quality / accuracy of work',
                  'rating_reliability': 'Reliability / accountability',
                  'rating_teamwork': 'Teamwork / collaboration',
                  'recommend': 'Would you recommend the candidate for the position they have '
                               'applied for at SSL Wireless?',
                  'recommend_explanation': 'Please explain your recommendation',
                  'referee_contact': 'Mobile / office contact',
                  'referee_designation': 'Your designation',
                  'referee_email': 'Official e-mail',
                  'referee_name': 'Your name',
                  'referee_organisation': 'Organisation',
                  'referee_relationship': 'Your relationship to the candidate',
                  'response_to_pressure': 'How did the candidate respond to feedback, pressure or '
                                          'changing priorities?',
                  'strongest_qualities': "What would you consider the candidate's strongest "
                                         'professional qualities?',
                  'worked_together_when': 'Approximately when did you work with the candidate?'}}

LEGACY_CHOICES = {'employer': {'disciplinary_action': {'no': 'No',
                                      'not_known': 'Not known / Not disclosed',
                                      'yes': 'Yes'},
              'employment_status': {'consultant': 'Consultant',
                                    'contractual': 'Contractual',
                                    'not_disclosed': 'Not disclosed',
                                    'other': 'Other',
                                    'outsourced': 'Outsourced',
                                    'permanent': 'Permanent',
                                    'probationer': 'Probationer'},
              'had_promotion': {'no': 'No', 'not_known': 'Not known / Not disclosed', 'yes': 'Yes'},
              'integrity_concerns': {'no': 'No',
                                     'not_known': 'Not known / Not disclosed',
                                     'yes': 'Yes'},
              'rating_attendance': {'average': 'Average',
                                    'below_average': 'Below Average',
                                    'excellent': 'Excellent',
                                    'good': 'Good',
                                    'na': 'N/A'},
              'rating_communication': {'average': 'Average',
                                       'below_average': 'Below Average',
                                       'excellent': 'Excellent',
                                       'good': 'Good',
                                       'na': 'N/A'},
              'rating_overall': {'average': 'Average',
                                 'below_average': 'Below Average',
                                 'excellent': 'Excellent',
                                 'good': 'Good',
                                 'na': 'N/A'},
              'rating_people_management': {'average': 'Average',
                                           'below_average': 'Below Average',
                                           'excellent': 'Excellent',
                                           'good': 'Good',
                                           'na': 'N/A'},
              'rating_professionalism': {'average': 'Average',
                                         'below_average': 'Below Average',
                                         'excellent': 'Excellent',
                                         'good': 'Good',
                                         'na': 'N/A'},
              'rating_quality': {'average': 'Average',
                                 'below_average': 'Below Average',
                                 'excellent': 'Excellent',
                                 'good': 'Good',
                                 'na': 'N/A'},
              'rating_reliability': {'average': 'Average',
                                     'below_average': 'Below Average',
                                     'excellent': 'Excellent',
                                     'good': 'Good',
                                     'na': 'N/A'},
              'rating_stakeholders': {'average': 'Average',
                                      'below_average': 'Below Average',
                                      'excellent': 'Excellent',
                                      'good': 'Good',
                                      'na': 'N/A'},
              'rehire_eligible': {'conditional': 'Conditional / With reservations',
                                  'no': 'No',
                                  'not_disclosed': 'Not disclosed',
                                  'yes': 'Yes'},
              'separation_nature': {'end_of_contract': 'End of contract',
                                    'involuntary': 'Involuntary separation',
                                    'not_disclosed': 'Not disclosed',
                                    'other': 'Other',
                                    'redundancy': 'Redundancy / Restructure',
                                    'resignation': 'Voluntary resignation'},
              'verifier_relationship': {'direct_manager': 'Direct Manager',
                                        'hr': 'HR / People Team',
                                        'other_official': 'Other Authorised Official'},
              'was_employed': {'no': 'No', 'unable': 'Unable to verify', 'yes': 'Yes'}},
 'professional': {'conduct_concerns': {'no': 'No', 'unable': 'Unable to Comment', 'yes': 'Yes'},
                  'hire_again': {'no': 'No',
                                 'unable': 'Unable to comment',
                                 'yes': 'Yes',
                                 'yes_reservations': 'Yes, with reservations'},
                  'managed_others': {'na': 'Not applicable',
                                     'no': 'No',
                                     'not_known': 'Not known',
                                     'yes': 'Yes'},
                  'rating_communication': {'average': 'Average',
                                           'below_average': 'Below Average',
                                           'excellent': 'Excellent',
                                           'good': 'Good',
                                           'na': 'N/A'},
                  'rating_integrity': {'average': 'Average',
                                       'below_average': 'Below Average',
                                       'excellent': 'Excellent',
                                       'good': 'Good',
                                       'na': 'N/A'},
                  'rating_leadership': {'average': 'Average',
                                        'below_average': 'Below Average',
                                        'excellent': 'Excellent',
                                        'good': 'Good',
                                        'na': 'N/A'},
                  'rating_overall': {'average': 'Average',
                                     'below_average': 'Below Average',
                                     'excellent': 'Excellent',
                                     'good': 'Good',
                                     'na': 'N/A'},
                  'rating_pressure': {'average': 'Average',
                                      'below_average': 'Below Average',
                                      'excellent': 'Excellent',
                                      'good': 'Good',
                                      'na': 'N/A'},
                  'rating_problem_solving': {'average': 'Average',
                                             'below_average': 'Below Average',
                                             'excellent': 'Excellent',
                                             'good': 'Good',
                                             'na': 'N/A'},
                  'rating_professionalism': {'average': 'Average',
                                             'below_average': 'Below Average',
                                             'excellent': 'Excellent',
                                             'good': 'Good',
                                             'na': 'N/A'},
                  'rating_quality': {'average': 'Average',
                                     'below_average': 'Below Average',
                                     'excellent': 'Excellent',
                                     'good': 'Good',
                                     'na': 'N/A'},
                  'rating_reliability': {'average': 'Average',
                                         'below_average': 'Below Average',
                                         'excellent': 'Excellent',
                                         'good': 'Good',
                                         'na': 'N/A'},
                  'rating_teamwork': {'average': 'Average',
                                      'below_average': 'Below Average',
                                      'excellent': 'Excellent',
                                      'good': 'Good',
                                      'na': 'N/A'},
                  'recommend': {'no': 'No',
                                'unable': 'Unable to assess',
                                'yes': 'Yes',
                                'yes_reservations': 'Yes, with reservations'},
                  'referee_relationship': {'client': 'Client / Stakeholder',
                                           'direct_manager': 'Direct Manager',
                                           'hr': 'HR',
                                           'other': 'Other',
                                           'peer': 'Peer',
                                           'skip_level_manager': 'Skip-level Manager'}}}
