# Generated by Django 5.2.16 on 2026-09-16 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_job_assessments'),
        ('sei_assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seiassessment',
            name='instrument',
            field=models.CharField(db_index=True, default='sei', max_length=32),
        ),
        migrations.AlterField(
            model_name='seiassessment',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.resume'),
        ),
        migrations.AddConstraint(
            model_name='seiassessment',
            constraint=models.UniqueConstraint(fields=('resume', 'instrument'), name='one_sitting_per_instrument'),
        ),
    ]
