# Generated by Django 5.2.16 on 2026-09-16 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_job_assessments'),
        ('sei_assessment', '0002_seiassessment_instrument_alter_seiassessment_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seiassessment',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sittings', to='core.resume'),
        ),
    ]
