# Generated by Django 5.2.16 on 2026-09-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sei_assessment', '0005_move_delivery_to_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentinvitation',
            name='consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
