# Generated by Django 5.2.15 on 2026-06-10 07:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_add_email_phone_to_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('1', 'Interview 1'), ('2', 'Interview 2'), ('3', 'Interview 3')], default='1', max_length=5)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='core.resume')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('interviewer_name', models.CharField(max_length=200)),
                ('interviewer_position', models.CharField(blank=True, max_length=200)),
                ('interviewer_department', models.CharField(blank=True, max_length=200)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('impression', models.CharField(blank=True, max_length=200)),
                ('recommendation', models.CharField(blank=True, choices=[('yes', 'Yes — Hire'), ('no', 'No — Reject'), ('maybe', 'Maybe — Further Review')], max_length=10)),
                ('priority_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('another_phase_required', models.BooleanField(default=False)),
                ('hard_negotiation', models.BooleanField(default=False)),
                ('suitable_other_dept', models.BooleanField(default=False)),
                ('suitable_higher_position', models.BooleanField(default=False)),
                ('suitable_junior_position', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='interviews.interview')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
