# Generated by Django 5.2.15 on 2026-06-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_soft_delete_and_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='is_deleted',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
