# Generated by Django 5.2.15 on 2026-06-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_fix_is_deleted_db_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewevaluation',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('yes', 'Yes - Hire'), ('no', 'No - Reject'), ('maybe', 'Maybe - Further Review')], max_length=10),
        ),
    ]
