# Generated by Django 5.2.16 on 2026-10-01 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_alter_interviewevaluation_recommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-scheduled_date', '-scheduled_time']},
        ),
        migrations.AddField(
            model_name='interview',
            name='candidate_email_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='interview',
            name='candidate_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='candidate_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 minutes'), (45, '45 minutes'), (60, '1 hour'), (90, '1 hour 30 minutes'), (120, '2 hours')], default=60),
        ),
        migrations.AddField(
            model_name='interview',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='interview',
            name='mode',
            field=models.CharField(choices=[('in_person', 'In person'), ('online', 'Online')], default='in_person', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='notify_candidate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewevaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewevaluation',
            name='interviewer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='interviewevaluation',
            name='invite_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='interviewevaluation',
            name='invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewevaluation',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
