# Generated by Django 5.2.15 on 2026-06-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_alter_interviewevaluation_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewevaluation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewevaluation',
            name='is_deleted',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
