# Generated by Django 5.2.16 on 2026-10-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_interview_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='schedule_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
