# Generated by Django 5.2.15 on 2026-07-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_interviewevaluation_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Optional. Leave empty for an all-day/unspecified slot.', null=True),
        ),
    ]
